---
- name: "Installing Apache webserver & hosting A Simple Site"
  hosts: amazon
  become: true
  tasks:

    - name: "Installing Apache and Mysql"
      yum:
        name: [ httpd , php, mariadb-server]
        state: present

    - name: "Creating httpd.conf from template"
      template:
        src: "httpd.conf.tmpl"
        dest: "/etc/httpd/conf/httpd.conf"
        owner: "root"
        group: "root"

 
    - name: Creating my.cnf from template
      template:
        src: "my.conf.tmpl"
        dest: "/etc/my.cnf"
        owner: "root"
        group: "root"      

    - name: "Restarting/Enabling httpd Service"
      service:
        name: httpd
        state: restarted
        enabled: true

    - name: "Restarting/Enabling mariadb Service"
      service:
        name: mariadb
        state: restarted
        enabled: true
